[package]
name = "swc_ts_types"
version = "0.1.0"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_atoms = { path = "../../atoms" }
swc_common = { path = "../../common" }
swc_visit = { path = "../../visit" }
swc_ecma_ast = { path = "../../ecmascript/ast" }
swc_ecma_utils = { path = "../../ecmascript/utils" }
is-macro = "0.1.7"
fxhash = "0.2.1"