[package]
name = "swc_bundler"
version = "0.1.0"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
concurrent = ["swc_common/concurrent", "dashmap", "rayon"]


[dependencies]
swc_atoms = { path = "../atoms" }
swc_common = { path = "../common" }
swc_ecma_ast = { path = "../ecmascript/ast" }
swc_ecma_codegen = { path = "../ecmascript/codegen" }
swc_ecma_parser = { path = "../ecmascript/parser" }
swc_ecma_transforms = { path = "../ecmascript/transforms" }
swc_ecma_utils = { path = "../ecmascript/utils" }
swc_ecma_visit = { path = "../ecmascript/visit" }
anyhow = "1"
crc = "1.8"
radix_fmt = "1"

log = "0.4"
petgraph = "0.5"
once_cell = "1"
dashmap = { version = "=3.5.1", optional = true }
rayon = { version = "1", optional = true }
fxhash = "0.2.1"
is-macro = "0.1"

[dev-dependencies]
testing = { path = "../testing" }